db-path:    ~/opt/bl/f451/tmp/out_dir
ffmpeg-bin: ~/opt/src/ffmpeg/git/ffmpeg/objs/inst/bin/ffmpeg

dvr-host: null # 127.0.0.1 # 
# добавлять в начале пакета 0x0000f451 для проверки синхронизации
insert_dvr_magic_number: true

logging_level:
  tornado.access: INFO
  tornado.application: INFO
  stream: INFO
  DVRReader: INFO
  DVRWriter: INFO

# для тестирования мультикаста "на живую"
#cast_one_source: udp://239.0.0.5:1234 # 239 - после транскодера
#cast_one_source: udp://235.3.3.3:8888 # некий tsplay
#cast_one_source: udp://236.1.1.1:1234 # cразу после "декриптора"

is_test: true
#emulate_live: true
#use_sendfile: true

multibitrate_testing: false

# если true, то вещание идет "по требованию", по умолчанию false;
stream_by_request: true

# вещать все каналы из конфига udp-source.yaml, если не stream_by_request,
# по умолчанию false; список stream-always-lst игнорируется
#stream_all_channels: true

log-path: ~/opt/bl/f451/git/log

#do_profiling: true

run-web-workers: true # false # 
#web-workers-count: -1

stream-always-lst:
  - pervyj
