# куда записывать чанки для live
db-path: /vagrant/f451/tmp/live

# путь до ffmpeg=нарезателя чанков
ffmpeg-bin: /home/vany/ffmpeg/objs/inst/bin/ffmpeg

# адрес сервера DVR; если пусто или null, то DVR не пишется
dvr-host: 127.0.0.1

# работа в тестовом/нет режиме (для разработчиков)
# (сделать по умолчанию false, когда выйдет в production)
is_test: true

# если true, то вещание идет "по требованию", по умолчанию false;
#stream_by_request: false

# вещать все каналы из конфига udp-source.yaml, если не stream_by_request,
# по умолчанию false; список stream-always-lst игнорируется
#stream_all_channels: false

# вещать часть каналов из конфига udp-source.yaml; при чтении опции stream-range 
# выбирается один из вариантов - names, part, ... size
# stream-always-lst в этом случае игнорируется
#stream-range:
  # вещание каналов по именам, синтаксис разделителей "-," такой же, как
  # у варианта "part"
  #names: ntv-pervyj, rossia1
  
  # если есть part: P/Q, то список делится на Q частей и вещается P-я часть каналов (1 <= P <= Q);
  # P может быть не только числом, но и списком с запятой-разделителем; пример: 1,4-6/6 => вещаются
  # 1, 4, 5 и 6я части
  #part: 2/3

  # аналогично part, только yaml-синтаксис для разделения на числа
  #python: [[1, [4, 6]], 6]
  
  # если есть size: K, то вещаются первые K каналов
  #size: 80

# в каких форматах вещать
#stream_hls: true
#stream_hds: true

# HTTP-порт
#port: 9451

# уровни логирования:
# - по умолчанию пишется с указанными настройками
# - можно добавить свой, с произвольным именем
logging_level:
  #tornado.access: WARNING
  #stream: INFO
  #DVRReader: INFO
  #DVRWriter: INFO

# вещать по ссылкам как у Wowza, например,
# /live/_definst_/smil:discoverychannel_sd/manifest.f4m ; по умолчанию true
#wowza-links: true

# куда писать логи, по умолчанию /var/log/451
#log-path: ~/opt/bl/f451/git/log

# запускать отдельные (рабочие) процессы для раздачи web-а; иначе основной процесс занимается
# не только слежением за chunker'ами, но и раздачей
#run-web-workers: true

# кол-во запускаемых рабочих процессов; если -1, то будет запущено max(cpu_count-1, 1)
# процессов (одно ядро - для основного процесса)
#web-workers-count: -1

# внешние ссылки на сам сервер вещания и на DVR-сервер; например, HDS не умеет
# ходить по корневым ссылкам (почему-то) вида "/path/to/something", поэтому приходится
# заводить абсолютные; формат ссылок - без слеша в конце
#www-dvr-server:

# ссылка на сам сервер; по умолчанию = www-dvr-server
#www-stream-server:

# лог ошибок в Sentry, по умолчанию в vladimirsky-sentry.bradburylab.tv
#sentry-dsn: null

########################### 
# Недокументированные опции

version: 0.01

#max_total: 72
#use_sendfile: false
#real_hds_chunking: true
#multibitrate_testing: true
#emulate_live: true
#do_write_dvr: true
#do_profiling: true
#insert_dvr_magic_number: true

################### 
# stream-always-lst

# по умолчанию равен ['pervyj']
stream-always-lst:
  - pervyj
